name: CI

on:
  # на каждый пуш в любую ветку
  push:                      
    branches: [ "*" ]
  # на каждый PR в любую ветку
  pull_request:              
    branches: [ "*" ]

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest

    steps:
      # 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.3"   # использовать версию Python 3.12.3

      - name: Install dependencies
        run: |
          # инсталируем библиотеки из requirements.txt
          pip install -r module_30_ci_linters/homework/hw1/requirements.txt
          # импортируем линтеры/типы
          pip install flake8 isort black mypy

      # Black: проверка форматирования (без авто-исправления в CI)
      - name: Black check
        run: black --check .

      # Isort: проверка сортировки импортов
      - name: Isort check
        run: isort --check-only --diff .

      # Flake8: стиль и простые ошибки
      - name: Flake8 check
        run: flake8 .

      # Mypy: статическая типизация
      - name: Mypy check
        run: mypy .
